### ISSUE TITLE
Wrong alg value

### ISSUE THREAD

**Issue by leftkaramolegos** [swift-server/sswg#105]
I'm running this code

        let jwe = try! JSONWebEncryption(
            content: Data("Live long and prosper.".utf8),
            keyEncryptingAlgorithm: .direct,
            keyEncryptionKey: nil,
            contentEncryptionAlgorithm: .aesEncryptionGCM256,
            contentEncryptionKey: kek
and the header outcome is {"typ":"JWE","alg":"direct","enc":"A256GCM"}
but the correct value for alg is "dir" (at least for my c# backend)

**Comment by 0xTim** [comment]
@leftkaramolegos which package are you using here? That's probably a better place to file an issue
